on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to check stuff
    steps:
      - uses: actions/checkout@v3
      - name: Install node dependencies
      	run: npm install -g write-good
      - id: foo
        uses: ./
      - run: echo "wrapping up"
        shell: bash
